# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_camera.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#GUI of Face recognition identtification and verification

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(961, 461)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(230, 226, 221);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(570, 180, 371, 241))
        self.groupBox.setStyleSheet("font: 87 12pt \"Lato Black\";")


        #GroupBox of right side which contain room_textEdit to display student name and time of attend
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 391, 71))
        self.label.setText("")
        self.label.setObjectName("label")
        self.room_textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.room_textEdit.setGeometry(QtCore.QRect(10, 20, 351, 201))
        self.room_textEdit.setObjectName("room_textEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 551, 331))
        self.groupBox_2.setStyleSheet("font: 87 12pt \"Lato Black\";")

        #The GroupBox 2 contain two screen of the camera
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 20, 271, 301))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_frame = QtWidgets.QLabel(self.groupBox_4)
        self.label_frame.setGeometry(QtCore.QRect(10, 20, 251, 271))
        self.label_frame.setText("")

        #Label where we will display enter camera which call label_frame
        self.label_frame.setObjectName("label_frame")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_5.setGeometry(QtCore.QRect(280, 20, 261, 301))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_frame_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_frame_2.setGeometry(QtCore.QRect(10, 20, 231, 281))
        self.label_frame_2.setText("")

        # Label where we will display exit camera which call label_frame_2
        self.label_frame_2.setObjectName("label_frame_2")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(10, 350, 111, 41))
        self.start.setStyleSheet("font: 87 10pt \"Lato Black\";\n"
"")
        #Start push button
        self.start.setObjectName("start")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(410, 350, 111, 41))
        self.exit.setStyleSheet("font: 87 10pt \"Lato Black\";")

        # Exit push button
        self.exit.setObjectName("exit")
        self.add_student = QtWidgets.QPushButton(self.centralwidget)
        self.add_student.setGeometry(QtCore.QRect(270, 350, 121, 41))
        self.add_student.setStyleSheet("font: 87 10pt \"Lato Black\";")

        # Student info push button
        self.add_student.setObjectName("add_student")
        self.end = QtWidgets.QPushButton(self.centralwidget)
        self.end.setGeometry(QtCore.QRect(140, 350, 111, 41))
        self.end.setStyleSheet("font: 87 10pt \"Lato Black\";")

        # End push button
        self.end.setObjectName("end")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(620, 0, 261, 111))
        self.groupBox_3.setStyleSheet("font: 87 12pt \"Lato Black\";")

        #GroupBox where we will dispaly the actual date and time
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 231, 80))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Time_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Time_label.setFont(font)

        #Label where we display the Time using label Date_label_4
        self.Time_label.setObjectName("Time_label")
        self.horizontalLayout_2.addWidget(self.Time_label)
        self.Date_label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Date_label_4.setFont(font)
        self.Date_label_4.setText("")
        self.Date_label_4.setObjectName("Date_label_4")
        self.horizontalLayout_2.addWidget(self.Date_label_4)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Date_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Date_label.setFont(font)

        # the label where we will display the date using Date_label3
        self.Date_label.setObjectName("Date_label")
        self.horizontalLayout.addWidget(self.Date_label)
        self.Date_label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Lato Black")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.Date_label_3.setFont(font)
        self.Date_label_3.setText("")
        self.Date_label_3.setObjectName("Date_label_3")
        self.horizontalLayout.addWidget(self.Date_label_3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.num_student = QtWidgets.QLCDNumber(self.centralwidget)
        self.num_student.setGeometry(QtCore.QRect(660, 120, 171, 61))

        #The LCD where we will display number of student present
        self.num_student.setObjectName("num_student")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)


        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 961, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Face Recognition Identification and Verification"))
        self.groupBox.setTitle(_translate("MainWindow", "Student Name"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Display"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Enter Camera"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Exit Camera"))
        self.start.setText(_translate("MainWindow", "START"))
        self.exit.setText(_translate("MainWindow", "EXIT"))
        self.add_student.setText(_translate("MainWindow", "STUDENT INFO"))
        self.end.setText(_translate("MainWindow", "END"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Date and Time"))
        self.Time_label.setText(_translate("MainWindow", "Time: "))
        self.Date_label.setText(_translate("MainWindow", "Date: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
